services:
  - type: web
    name: idr-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: idr-db
          property: connectionString
    plan: free
    region: oregon
    buildNpmVersion: 10.9.4
    envVars:
      - key: NODE_VERSION
        value: 18.x
